# Hugo build configuration for Netlify
# (https://gohugo.io/hosting-and-deployment/hosting-on-netlify/#configure-hugo-version-in-netlify)

[build]
command = "hugo --gc --minify"
publish = "public"

[build.environment]
HUGO_VERSION = "0.151.2"
GO_VERSION = "1.25.3"
NODE_VERSION = "24"

[context.production]
command = "hugo --gc --minify"

[context.production.environment]
HUGO_ENV = "production"
